jobs:
- job: Linux
  variables:
    python_version: '3.6'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: ci/azure-steps.yml
  strategy:
    matrix:
        Python38:
          python_version: '3.8'
        Python37:
          python_version: '3.7'
        Python36:
          python_version: '3.6'
- job: MacOS
  variables:
    python_version: '3.6'
  pool:
    vmImage: 'macos-10.14'
  steps:
    - template: ci/azure-steps.yml
- job: Windows
  variables:
    python_version: '3.6'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
    - template: ci/azure-steps.yml
- job: Docs
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: ci/azure-docs.yml

trigger:
  branches:
    include:
    - master
    - vnext
  tags:
    include:
    - '*'

pr:
- master
