name: py38-sparse-test
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytest
  - numpy
  - scipy
  - pytest-cov
  - nomkl
  - numba
  - black
  - codecov
  - pip:
    - pytest-black
